---
swagger: "2.0"
info:
  title: Crunchyroll Notifier
  description: API for Crunchyroll Notifier application
  version: 1.0.0
basePath: "/"
paths:
  "/api/crunchylists":
    get:
      summary: GetCrunchyLists Function
      description: Gets all your custom lists from Crunchyroll
      operationId: GetCrunchyLists
      produces:
        - application/json
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCrunchyListsFunction.Arn}/invocations"
      security:
        - api_key: []
  "/api/crunchylists/{id}":
    get:
      summary: GetCrunchyList Function
      description: Gets a custom list from Crunchyroll by id
      operationId: GetCrunchyList
      produces:
        - application/json
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCrunchyListFunction.Arn}/invocations"
      security:
        - api_key: []
  "/api/recently-added":
    get:
      summary: GetRecentlyAdded Function
      description: Gets recently added items from Crunchyroll
      operationId: GetRecentlyAdded
      produces:
        - application/json
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetRecentlyAddedFunction.Arn}/invocations"
      security:
        - api_key: []
  "/api/recently-added/notifications":
    get:
      summary: GetRecentlyAddedNotifications Function
      description: Gets notification data for recently added items from Crunchyroll
      operationId: GetRecentlyAddedNotifications
      produces:
        - application/json
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetRecentlyAddedNotificationsFunction.Arn}/invocations"
      security:
        - api_key: []
"/api/recently-added/notify":
    get:
      summary: NotifyOnRecentlyAdded Function
      description: Notifies of newly released anime from Crunchyroll
      operationId: NotifyOnRecentlyAdded
      produces:
        - application/json
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NotifyOnRecentlyAddedFunction.Arn}/invocations"
      security:
        - api_key: []
schemes:
  - https
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
    x-amazon-apigateway-api-key-source: HEADER
