AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for WatchWizard Application
Globals:
  Function:
    Runtime: python3.9
    Timeout: 60
    Environment:
      Variables:
        ServiceName: !Ref ServiceName
        SecretName: !Sub "apps/${ServiceName}"
        SecretsManagerEndpoint: ""
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - Dev
      - QA
      - Prod
    Default: Dev
  ServiceName:
    Type: String
    Default: CrunchyrollNotifier
  NotificationSound:
    Type: String
    Default: classical

Conditions:
  IsDev: !Equals 
    - !Ref Environment
    - Dev
  IsNotDev: !Not
    - !Equals 
      - !Ref Environment
      - Dev

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Condition: IsNotDev
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/SecretsViewOnly
            
  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Condition: IsNotDev
    Properties:
      Name: !Sub "apps/${ServiceName}"
      Description: !Sub "Secret values for the ${ServiceName} application"
      SecretString: '{"CrunchyrollEmail": "", "CrunchyrollPassword": "", "CrunchyrollListId": "", "PushoverUser": "", "PushoverToken": ""}'

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Name: !Sub "${ServiceName}-ApiGateway"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: "./api.yaml"
      MethodSettings:
      - LoggingLevel: ERROR
        ResourcePath: "/*"
        HttpMethod: "*"

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Condition: IsNotDev
    Properties:
      UsagePlanName: !Sub "${ServiceName}-Default-Usage-Plan"
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref ApiGatewayApi.Stage
      Description: !Sub "Default usage plan for the ${ServiceName} service"
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Condition: IsNotDev
    Properties:
      Name: !Sub "${ServiceName}-Default-API-Key"
      Description: !Sub "Default API key for the ${ServiceName} service"
      Enabled: True
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: !Ref ApiGatewayApi.Stage

  UsagePlanApiKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Condition: IsNotDev
    Properties: 
      KeyId: !Ref ApiKey
      KeyType: 'API_KEY'
      UsagePlanId: !Ref UsagePlan

  GetCrunchyListsFunction:
    Type: AWS::Serverless::Function
    Condition: IsNotDev
    Properties:
      FunctionName: !Sub "${ServiceName}-GetCrunchyLists"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: crunchyroll_notifier/
      Handler: handlers/api_handler.get_crunchylists
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/api/crunchylists"
            Method: get
            Auth:
              ApiKeyRequired: true
  
  GetCrunchyListFunction:
    Type: AWS::Serverless::Function
    Condition: IsNotDev
    Properties:
      FunctionName: !Sub "${ServiceName}-GetCrunchyList"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: crunchyroll_notifier/
      Handler: handlers/api_handler.get_crunchylist
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/api/crunchylists/{id}"
            Method: get
            Auth:
              ApiKeyRequired: true

  MockGetCrunchyListsFunction:
    Type: AWS::Serverless::Function
    Condition: IsNotDev
    Properties:
      FunctionName: !Sub "${ServiceName}-MockGetCrunchyLists"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: crunchyroll_notifier/
      Handler: handlers/mock_api_handler.get_crunchylists
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/mock/api/crunchylists"
            Method: get
            Auth:
              ApiKeyRequired: true

  MockGetCrunchyListFunction:
    Type: AWS::Serverless::Function
    Condition: IsDev
    Properties:
      FunctionName: !Sub "${ServiceName}-MockGetCrunchyList"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: crunchyroll_notifier/
      Handler: handlers/mock_api_handler.get_crunchylist
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/mock/api/crunchylists/{id}"
            Method: get
            Auth:
              ApiKeyRequired: true

Outputs:
  CrunchyrollNotifierApi:
    Description: "API Gateway URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"